---
- name: Configuring the EC2 Instance
  hosts: localhost
  connection: local
  vars:
    volumes: 
      - device_name: /dev/sda1
        volume_size: 10

  tasks:
    - name: Launching an EC2 Instance
      local_action: ec2
         instance_type={{ instance_type }}
         image={{ ami }}
         region={{ region }}
         keypair={{ pem }}
         count={{ count }}
         group={{ security_group }}
         wait=true
         volumes={{ volumes }}
      register: ec2

# run playbook with below info
#ansible-playbook create_ec2.yml --extra-vars instance_type=t2.micro -e region=ap-southeast-1 -e pem=DevOps -e count=1 -e ami=ami-0d53ac3145db0eace -e security_group=DevOps-SG
